### ISSUE TITLE
classic support?

### ISSUE THREAD

**Issue by k99k5** [Tercioo/FlashTaskBar#1]

**Comment by vanillalad** [comment]
I've ported it to classic on my fork: https://github.com/vanillalad/FlashTaskBar
In terms of functionality everything is the same, except that I removed mob scan. Mob scan has to be rewritten for classic.

**Comment by infekSK** [comment]
> 
> 
> I've ported it to classic on my fork: https://github.com/vanillalad/FlashTaskBar
> In terms of functionality everything is the same, except that I removed mob scan. Mob scan has to be rewritten for classic.

Apologies on necroing a thread but I wasn't able to make an issue on your fork. Any chances it could be updated to TBCC?

**Comment by Tercioo** [comment]
yes

------ Original Message ------

**Comment by infekSK** [comment]
The fork VanillaLad works, but there's an issue with the Locale apparently, just a big red box in the middle of the screen. Wasn't too sure how to fix it.
