### ISSUE TITLE
pre-patch errors - FlashTaskBar\libs\DF\cooltip.lua:169: attempt to call method 'SetBackdrop' (a nil value)

### ISSUE THREAD

**Issue by zmoose** [Tercioo/FlashTaskBar#3]
For developers, see https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes#backdrop-system-changes

1x FlashTaskBar\libs\DF\cooltip.lua:169: attempt to call method 'SetBackdrop' (a nil value)
[string "@FlashTaskBar\libs\DF\cooltip.lua"]:169: in function `build_main_frame'
[string "@FlashTaskBar\libs\DF\cooltip.lua"]:290: in function `CreateCoolTip'
[string "@FlashTaskBar\libs\DF\cooltip.lua"]:3413: in main chunk

Locals:
self = GameCooltipFrame1 {
 0 = <userdata>
 FlashAnimation = <unnamed> {
 }
 Stop = <function> defined @FlashTaskBar\libs\DF\fw.lua:653
 SetBorderColor = <function> defined @FlashTaskBar\libs\DF\fw.lua:2294
 SetLayerVisibility = <function> defined @FlashTaskBar\libs\DF\fw.lua:2306
 Borders = <table> {
 }
 SetBorderAlpha = <function> defined @FlashTaskBar\libs\DF\fw.lua:2278
 Flash = <function> defined @FlashTaskBar\libs\DF\fw.lua:658
}
(*temporary) = nil
(*temporary) = GameCooltipFrame1 {
 0 = <userdata>
 FlashAnimation = <unnamed> {
 }
 Stop = <function> defined @FlashTaskBar\libs\DF\fw.lua:653
 SetBorderColor = <function> defined @FlashTaskBar\libs\DF\fw.lua:2294
 SetLayerVisibility = <function> defined @FlashTaskBar\libs\DF\fw.lua:2306
 Borders = <table> {
 }
 SetBorderAlpha = <function> defined @FlashTaskBar\libs\DF\fw.lua:2278
 Flash = <function> defined @FlashTaskBar\libs\DF\fw.lua:658
}
(*temporary) = <table> {
 bgFile = "DialogFrame\UI-DialogBox-Background-Dark"
 tileSize = 16
 edgeFile = "Buttons\WHITE8X8"
 tile = true
 edgeSize = 1
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
DF = <table> {
 DropDownCounter = 434238
 ClassCache = <table> {
 }
 GetAsianNumberSymbols = <function> defined @FlashTaskBar\libs\DF\fw.lua:414
 CreateAnts = <function> defined @FlashTaskBar\libs\DF\fw.lua:2237
 NewLabel = <function> defined @FlashTaskBar\libs\DF\label.lua:258
 PanelCounter = 434238
 PictureNameCounter = 434238
 GetTemplate = <function> defined @FlashTaskBar\libs\DF\fw.lua:1627
 ClientLanguage = "enUS"
 SetHook = <function> defined @FlashTaskBar\libs\DF\fw.lua:1674
 GetCurrentSpec = <function> defined @FlashTaskBar\libs\DF\fw.lua:2656
 CheckPoints = <function> defined @FlashTaskBar\libs\DF\fw.lua:713
 GetRangeValue = <function> defined @FlashTaskBar\libs\DF\math.lua:57
 GetCooldownInfo = <function> defined @FlashTaskBar\libs\DF\spells.lua:781
 ScheduleTimer = <function> defined @AnnounceRare\Libraries\Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 NewTextEntry = <function> defined @FlashTaskBar\libs\DF\textentry.lua:536
 EncodeString = <function> defined @FlashTaskBar\libs\DF\textentry.lua:1241
 SortOrder3R = <function> defined @FlashTaskBar\libs\DF\fw.lua:636
 Msg = <function> defined @FlashTaskBar\libs\DF\fw.lua:609
 PrintVersion = <function> defined @FlashTaskBar\libs\DF\fw.lua:140
 CreateScrollBar = <function> defined @FlashTaskBar\libs\DF\scrollbar.lua:7
 CreateGlowOverlay = <function> defined @FlashTaskBar\libs\DF\fw.lua:2192
 UnitGroupRolesAssigned = <function> defined @FlashTaskBar\libs\DF\fw.lua:53
 ShowTutorialAlertFrame = <function> defined @FlashTaskBar\libs\DF\fw.lua:1298
 CooldownsExternals = <table> {
 }
 GetSpecializationRole = <function> defined @FlashTaskBar\libs\DF\fw.lua:89
 SpecListByClass = <table> {
 }
 FRAMELEVEL_BACKGROUND = 150
 RunHooksForWidget = <function> defined @FlashTaskBar\libs\DF\fw.lua:1656
 IntegerToTimer = <function> defined @FlashTaskBar\libs\DF\fw.lua:489
 SortOrder1 = <function> defined @FlashTaskBar\libs\DF\fw.lua:621
 GetDefaultColorList = <function> defined @FlashTaskBar\libs\DF\colors.lua:170
 button_templates = <table> {
 }
 NewSwitch = <function> defined @FlashTaskBar\libs\DF\slider.lua:942
 ReskinSlider = <function> defined @FlashTaskBar\libs\DF\fw.lua:2523
 GetBestFontForLanguage = <function> defined @FlashTaskBar\libs\DF\fw.lua:1497
 CreateColorTable = <function> defined @FlashTa

**Comment by zmoose** [comment]
1x FlashTaskBar\libs\DF\button.lua:1045: attempt to call method 'SetBackdropColor' (a nil value)
[string "@FlashTaskBar\libs\DF\slider.lua"]:963: in function `NewSwitch'
[string "@FlashTaskBar\libs\DF\fw.lua"]:1006: in function `BuildMenu'
[string "@FlashTaskBar\FlashTaskBar.lua"]:936: in function <FlashTaskBar\FlashTaskBar.lua:121>
[string "=[C]"]: in function `xpcall'
[string "@FlashTaskBar\libs\DF\addon.lua"]:55: in function <FlashTaskBar\libs\DF\addon.lua:15>
[string "=[C]"]: ?
[string "@AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...nceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <...nceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by alexnaumovich** [comment]
Yes, there are many calls to SetBackdrop and SetBackdropColor in the DF library, all of them are broken.

**Comment by Daeveren** [comment]
For me it stopped throwing errors when I've used the DF fork from here https://github.com/Tercioo/Details-Framework/tree/shadowlands - basically get this Details! Framework version and replace inside the /libs/DF

**Comment by alexnaumovich** [comment]
Can confirm, downloading DF library fixes the problem.

**Comment by zmoose** [comment]
> For me it stopped throwing errors when I've used the DF fork from here https://github.com/Tercioo/Details-Framework/tree/shadowlands - basically get this Details! Framework version and replace inside the /libs/DF

Thanks that worked for me as well.
