### ISSUE TITLE
hooksecurefunction

### ISSUE THREAD

**Issue by Pahn1988** [Tercioo/FlashTaskBar#5]
2x FlashTaskBar\FlashTaskBar.lua:212: hooksecurefunc(): HelpFrame_OnEvent is not a function
[string "@FlashTaskBar\FlashTaskBar.lua"]:212: in function <FlashTaskBar\FlashTaskBar.lua:121>
[string "=[C]"]: in function `xpcall'
[string "@FlashTaskBar\libs\DF\addon.lua"]:55: in function <FlashTaskBar\libs\DF\addon.lua:15>
[string "=[C]"]: ?
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Ace3\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by dartraiden** [comment]
Yes, no more HelpFrame_OnEvent
https://github.com/Gethe/wow-ui-source/commit/6b74238b2eb64bf1ead43eb6208501411b218344

now it's `function HelpFrameMixin:OnEvent(event, ...)`

**Comment by Tercioo** [comment]
fixed
