### ISSUE TITLE
[10.0] Options interface is broken

### ISSUE THREAD

**Issue by dartraiden** [Tercioo/FlashTaskBar#6]
![Wow_IobX4DJ4h5](https://user-images.githubusercontent.com/5046855/198059708-ade97ae3-b677-43a2-a8d4-9d991b285d7e.jpg)

**Comment by Tercioo** [comment]
Thank you for reporting!

------ Original Message ------
From: "Alexander Gavrilov" ***@***.***>
To: "Tercioo/FlashTaskBar" ***@***.***>
Cc: "Subscribed" ***@***.***>
Sent: 26-Oct-22 11:52:06 AM
Subject: [Tercioo/FlashTaskBar] [10.0] Options interface is broken 
(Issue #6)

**Comment by Daeveren** [comment]
It's because one of the libs (LibDFramework-1.0) is not updated.

Fix is to go to AddOns\FlashTaskBar\libs\DF\ and copy in there the contents from the latest file you download from
https://www.curseforge.com/wow/addons/libdframework/files/all

This also fixes the lua error at login

**Comment by GurliGebis** [comment]
I have created a PR that updates the library
